# Generated by Django 4.1.6 on 2023-02-19 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Почта')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Город')),
                ('building_number', models.CharField(max_length=10, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True, verbose_name='Название продукта')),
                ('product_model', models.CharField(max_length=100, verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Название продукта',
                'verbose_name_plural': 'Название продуктов',
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название организации')),
                ('level', models.SmallIntegerField(choices=[(0, 'Завод'), (1, 'Дистрибьютор'), (2, 'Оптовый склад'), (3, 'Розничная сеть'), (4, 'Индивидуальный предприниматель')], verbose_name='Тип организации')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Задолженность')),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Дата выхода на рынок')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='firm.contact')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('product', models.ManyToManyField(related_name='firm', to='firm.product')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traders', to='firm.firm', verbose_name='Поставщик')),
            ],
        ),
    ]
